version: "3.9"

services:
  # --- Text classifier ---
  text-classifier:
    build:
      context: ./text-classifier
      dockerfile: Dockerfile
    environment:
      CLASSIFY_CATEGORY_URL: ${CLASSIFY_CATEGORY_URL}
    container_name: text-classifier
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - backend

  # --- API ---
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: api
    env_file:
      - .env
    expose:
      - "8080"
    restart: always
    volumes:
      - ./files:/app/files
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend

  # --- Tracker ---
  tracker:
    build:
      context: .
      dockerfile: cmd/tracker/Dockerfile
    container_name: tracker
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/sa-key.json
      BASE_TRANSACTION_URL: ${BASE_TRANSACTION_URL}
    restart: always
    volumes:
      - ./files:/app/files
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend

  # --- Frontend (Next.js) ---
  frontend:
    build:
      context: ./frontends/transactions-dashboard
      dockerfile: Dockerfile
    container_name: transactions-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
      - NEXT_LOGIN_URL=http://localhost:4321
    expose:
      - "3000"
    restart: always
    networks:
      - frontend
      - backend

  # --- Astro Frontend ---
  homepage:
    build:
      context: ./frontends/homepage
      dockerfile: Dockerfile
    container_name: transactions-home
    environment:
      - PUBLIC_API_BASE_URL=http://api:8080
    expose:
      - "4321"
    restart: always
    networks:
      - frontend
      - backend

  # --- Nginx ---
  nginx:
    image: nginx:1.25
    container_name: transactions-nginx
    # depends_on:
      # - api
      # - frontend
      # - homepage
    ports:
      - "8080:80"
      - "4321:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    restart: always
    networks:
      - frontend
      - backend

# --- Networks ---
networks:
  frontend:
  backend:
